name: "Build network"
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  id-token: write
  contents: read
  pull-requests: write 

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          role-session-name: ${{ secrets.AWS_OIDC_ROLE_SESSION_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5
          working-directory: ./terraform

      - name: Debug Secrets
        run: echo "Bucket: ${{ secrets.AWS_TFSTATE_BUCKET_NAME }}, Key: ${{ secrets.AWS_TFSTATE_KEY_NAME }}, Region: ${{ secrets.AWS_REGION }}"

      - name: Terraform fmt
        id: fmt
        working-directory: ./terraform
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_TFSTATE_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_TFSTATE_KEY_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: > 
          terraform init -backend-config="bucket=${{ secrets.AWS_TFSTATE_BUCKET_NAME }}" 
          -backend-config="key=${{ secrets.AWS_TFSTATE_KEY_NAME }}" 
          -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Validate
        id: validate
        working-directory: ./terraform
        run: terraform validate -no-color
